apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: devops-cluster
  region: us-east-1
  version: "1.27"    # BUG 1: EOL version — use 1.31

iam:
  withOIDC: true

managedNodeGroups:
  - name: ng-standard
    instanceType: t3.medium
    # BUG 3: missing minSize — defaults to 0
    maxSize: 5
    desiredCapacity: 2
    amiType: AL2_x86_64_GPU    # BUG 2: GPU AMI for standard workload — use AL2_x86_64
    iam:
      instanceRoleARN: "NodeRole"   # BUG 5: must be full ARN, not just role name
