name: Service CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    uses: ./.github/workflows/python-ci.yml
    with:
      python-version: "3.12"
      test-command: "pytest --verbose"
    secrets: inherit
