apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
spec:
  metrics:
    - name: success-rate
      interval: 1m
      failureLimit: 3
      provider:
        prometheus:
          address: http://prometheus-operated.monitoring.svc.cluster.local:9090
          query: |
            sum(rate(http_requests_total{status!~"5..",app="devops-app"}[5m])) /
            sum(rate(http_requests_total{app="devops-app"}[5m]))
      successCondition: result[0] >= 0.95
