apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: devops-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: devops-app
  template:
    metadata:
      labels:
        app: devops-app
    spec:
      containers:
        - name: app
          image: devops-app:1.2.0
          ports:
            - containerPort: 5000
  strategy:
    canary:
      maxSurge: "25%"
      maxUnavailable: 0
      steps:
        - setWeight: 10
        - pause:
            duration: 2m
        - analysis:
            templates:
              - templateName: success-rate
        - setWeight: 50
        - pause:
            duration: 2m
        - setWeight: 100
