apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: devops-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: devops-app
  template:
    metadata:
      labels:
        app: devops-app
    spec:
      containers:
        - name: app
          image: devops-app:1.2.0
          ports:
            - containerPort: 5000
  strategy:
    canary:
      maxSurge: 0        # BUG 2: no new pods can be created — rollout cannot progress
      maxUnavailable: 1
      steps: []          # BUG 1: empty steps — canary weight never changes
      # BUG 3: no pauseDuration between steps — would be instant even if steps existed
      # BUG 4: no analysis reference — no automated metric checking
      # BUG 5: AnalysisTemplate not created (see starter/analysis-template.yaml)
