name: CI

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      APP_ENV: test

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Validate required secrets
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          if [ -z "$API_KEY" ]; then
            echo "ERROR: API_KEY secret is not configured in this repository."
            echo "Add it via Settings → Secrets and variables → Actions."
            exit 1
          fi
          echo "Required secrets are present"

      - name: Install dependencies
        run: pip install -r requirements.txt pytest

      - name: Run tests
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: pytest
