AWSTemplateFormatVersion: "2010-09-09"
Description: Lambda + API Gateway

Resources:
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  MyFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: devops-api
      Runtime: python3.9          # BUG 1: deprecated — use python3.12
      Handler: main.handler       # BUG 2: file is lambda_function.py — should be lambda_function.handler
      MemorySize: 64              # BUG 5: below minimum 128 MB
      Timeout: 30
      Role: !GetAtt LambdaRole.Arn
      Code:
        ZipFile: |
          import json
          def handler(event, context):
              return {"statusCode": 200, "body": json.dumps({"message": "Hello!"})}

  # BUG 3: missing AWS::Lambda::Permission for API Gateway

  MyApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: devops-api

  MyResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref MyApi
      ParentId: !GetAtt MyApi.RootResourceId
      PathPart: hello

  MyMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref MyApi
      ResourceId: !Ref MyResource
      HttpMethod: GET
      AuthorizationType: NONE
      Integration:
        Type: HTTP           # BUG 4: should be AWS_PROXY for Lambda proxy integration
        IntegrationHttpMethod: POST
        Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${MyFunction.Arn}/invocations"
