AWSTemplateFormatVersion: "2010-09-09"
Description: RDS PostgreSQL with Secrets Manager

Resources:
  DBSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: prod/db/password
      GenerateSecretString:
        SecretStringTemplate: '{"username": "admin"}'
        GenerateStringKey: password
        PasswordLength: 32
        ExcludeCharacters: '"@/\'

  DBParameterGroup:
    Type: AWS::RDS::DBParameterGroup
    Properties:
      DBParameterGroupFamily: postgres15   # FIX 3: matches EngineVersion
      Description: PostgreSQL 15 parameters

  MyDB:
    Type: AWS::RDS::DBInstance
    Properties:
      Engine: postgres
      EngineVersion: "15.4"               # FIX 1: include patch version
      DBInstanceClass: db.t3.micro
      AllocatedStorage: "20"
      MasterUsername: admin
      MasterUserPassword: !Sub "{{resolve:secretsmanager:${DBSecret}:SecretString:password}}"
      PubliclyAccessible: false           # FIX 2: private database
      DBParameterGroupName: !Ref DBParameterGroup
      BackupRetentionPeriod: 7
    DeletionPolicy: Snapshot
