name: Deploy

on:
  push:
    branches: [main]

concurrency:
  group: deploy-production
  cancel-in-progress: false

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
      - run: pip install -r requirements.txt pytest && pytest

  deploy-staging:
    needs: test
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: ${{ vars.STAGING_URL }}
    steps:
      - run: echo "Deploying to staging at $STAGING_URL..."
        env:
          STAGING_URL: ${{ vars.STAGING_URL }}

  deploy-prod:
    needs: deploy-staging
    runs-on: ubuntu-latest
    environment:
      name: production
      url: ${{ vars.PROD_URL }}
    steps:
      - run: echo "Deploying to production at $PROD_URL..."
        env:
          PROD_URL: ${{ vars.PROD_URL }}
