name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          # BUG 1 & 3: Add cache: "pip" here
          # BUG 2 & 4: Add cache-dependency-path covering both requirements files

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest pytest-cov flake8

      - name: Lint
        run: flake8 .

      - name: Test
        run: pytest --cov=app --cov-report=xml
