name: Image Promotion Pipeline

on:
  workflow_dispatch:
    inputs:
      sha:
        description: "Git SHA to promote"
        required: true

jobs:
  promote:
    runs-on: ubuntu-latest
    env:
      IMAGE_SHA: ${{ inputs.sha }}
    steps:
      - name: Login to dev registry
        uses: docker/login-action@v3
        with:
          registry: dev.registry.io
          username: ${{ secrets.DEV_REGISTRY_USER }}
          password: ${{ secrets.DEV_REGISTRY_TOKEN }}

      - name: Login to production registry
        uses: docker/login-action@v3
        with:
          registry: prod.registry.io
          username: ${{ secrets.PROD_REGISTRY_USER }}
          password: ${{ secrets.PROD_REGISTRY_TOKEN }}

      - name: Scan image for vulnerabilities
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: dev.registry.io/devops-app:${{ env.IMAGE_SHA }}
          format: table
          severity: CRITICAL
          exit-code: "1"
          ignore-unfixed: true

      - name: Check tag does not already exist in production
        run: |
          if docker manifest inspect prod.registry.io/devops-app:$IMAGE_SHA 2>/dev/null; then
            echo "ERROR: tag $IMAGE_SHA already exists in production registry"
            exit 1
          fi

      - name: Pull from dev and push to production with SHA tag
        run: |
          docker pull dev.registry.io/devops-app:$IMAGE_SHA
          docker tag dev.registry.io/devops-app:$IMAGE_SHA \
            prod.registry.io/devops-app:$IMAGE_SHA
          docker push prod.registry.io/devops-app:$IMAGE_SHA

      - name: Install cosign
        uses: sigstore/cosign-installer@v3

      - name: Sign production image
        run: |
          cosign sign --key env://COSIGN_PRIVATE_KEY \
            prod.registry.io/devops-app:$IMAGE_SHA
        env:
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
