name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      # BUG 3: fail-fast defaults to true — add fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
        include:
          - python-version: "3.12"
            experimental: true

    # BUG 2: this syntax is wrong — should be: ${{ matrix.experimental == true }}
    continue-on-error: ${{ matrix.experimental }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"   # BUG 1: should be ${{ matrix.python-version }}

      - name: Install and test
        run: |
          pip install -r requirements.txt pytest
          pytest
